### ISSUE TITLE
Flutter: throws an error when running discoverDevices

### ISSUE THREAD

**Issue by nermolov** [SpinlockLabs/upnp.dart#1]
```
E/flutter (  616): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: SocketException: Failed listing interfaces (OS Error: Listing interfaces is not supported on this platform)
E/flutter (  616): #0      _NativeSocket.listInterfaces.<anonymous closure> (dart:io-patch/socket_patch.dart:414:9)
E/flutter (  616): #1      _rootRunUnary (dart:async/zone.dart:1132:38)
E/flutter (  616): #2      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter (  616): #3      _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
E/flutter (  616): #4      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
E/flutter (  616): #5      Future._propagateToListeners (dart:async/future_impl.dart:668:32)
E/flutter (  616): #6      Future._completeWithValue (dart:async/future_impl.dart:483:5)
E/flutter (  616): #7      Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:513:7)
E/flutter (  616): #8      _rootRun (dart:async/zone.dart:1124:13)
E/flutter (  616): #9      _CustomZone.run (dart:async/zone.dart:1021:19)
E/flutter (  616): #10     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
E/flutter (  616): #11     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
E/flutter (  616): #12     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
E/flutter (  616): #13     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
E/flutter (  616): 
```

Possibly related issue thread: https://github.com/flutter/flutter/issues/27346

**Comment by githubforsank** [comment]
Bump !

**Comment by githubforsank** [comment]
This issue has been opened since 1 year, Any update on this ?

**Comment by Niek** [comment]
Any workarounds?

**Comment by moda20** [comment]
How are you getting this error ? can you post a code snippet and whether you are running it in an isolate or not.
